server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://user-postgres:5432/userdb
    username: useradmin
    password: userpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
